### ISSUE TITLE
Error with stacked forum in last post

### ISSUE THREAD

**Issue by soft4tec** [tas2580/phpBB-3-1-SEO-URLs#10]
If you have subforums in your forum there is an in the link for the last post.
For Example
- Forum 1
  - SubForum
    - FirstPost

I found an quick&dirty solution in the **listener.php** for the function:

**public function display_forums_modify_template_vars($event)**

Replace the line:

``` php
$url = $this->generate_topic_link($event['row']['forum_id'], $event['row']['forum_name'], $event['row']['topic_id'], $event['row']['topic_title']);
```

with:

``` php
                $sql = 'SELECT p.post_id, p.topic_id, p.forum_id, f.forum_name
                        FROM ' . POSTS_TABLE . ' AS p
                        LEFT JOIN ' . FORUMS_TABLE . ' AS f
                        ON f.forum_id = p.forum_id
                        WHERE ' . $db->sql_build_array('SELECT', array('post_id'    => $event['row']['forum_last_post_id']));
                $result = $db->sql_query($sql);
                $LastPostRow = $db->sql_fetchrow($result);
                $db->sql_freeresult($result);
                $url = $this->generate_topic_link($LastPostRow['forum_id'], $LastPostRow['forum_name'], $LastPostRow['topic_id'], $event['row']['forum_last_post_subject']);
```

Maybe there is a better way to get the title and ids, but this works for the first.

**Comment by Sarr** [comment]
@soft4tec sorry but it doesn't work for me.
I get: "Fatal error: Call to a member function sql_build_array() on a non-object in /home/sarr/public_html/forum.swordcoast.pl/ext/tas2580/seourls/event/listener.php on line 184"

There are 2 occurance of
'$url = $this->generate_topic_link($event['row']['forum_id'], $event['row']['forum_name'], $event['row']['topic_id'], $event['row']['topic_title']);'

First is in "public function search_modify_tpl_ary($event)"
I changed only the second one, as you wrote. (under display_forums_modify_template_vars)

**Comment by soft4tec** [comment]
Oh sorry,
I forget the

**global $db;**

to access the Database-Object in the function. Then it should be work.

**Comment by tas2580** [comment]
Thanks for reporting, but your solution has the problem that it will make a lot of SQL queries. I have found a better way without additional SQL queries. I hope it will work.
