### ISSUE TITLE
The problem with Quick Mod Tools (moving topic, etc.)

### ISSUE THREAD

**Issue by Sarr** [tas2580/phpBB-3-1-SEO-URLs#17]
Hi. There is problem with using quick moderation tools. When you try to move a topic, you get an error of "not safe redirection" or something like that. It should be easy to replicate when you move existing topic to another forum via tools visible in Admins / Global Mods frontend, viewtopic.

**Comment by tas2580** [comment]
I have searched for an event to fix this, but there is none. The only way I know to fix this for the moment is to open viewtopic.php and search for
'redirect'    => urlencode(str_replace('&amp;', '&', $viewtopic_url)),
replace this line with
'redirect'    => urlencode(str_replace(array('&amp;', '../'), array('&', ''), $viewtopic_url)),

**Comment by Sarr** [comment]
Thank you. Maybe you could inform phpbb 3.1 team, and ask for some improvements in future versions? Your SEO ext is great, good job and big thanks.
Maybe not as roboust as phpbbseo ultimate (usu), but stable, so usable, and lightweight I guess.

**Comment by tas2580** [comment]
Fixed in 0.3.0
