### ISSUE TITLE
notification links

### ISSUE THREAD

**Issue by petters0n** [tas2580/phpBB-3-1-SEO-URLs#2]
forum/index.php?mark_notification=xxxx
changed automatically to 
forum/

**Comment by cloudgp** [comment]
Hi, I am having this issue as well using your mod, could you pls tell us if you are going to release a fix for this soon?

**Comment by Galixte** [comment]
Hi @tas2580,

Could you take a look, please ?

**Comment by Sarr** [comment]
I too have this problem. Notifications aren't giving proper links when they are unread, if they are marked as read - their links are fine.
