### ISSUE TITLE
Also update URLs for all other pages?

### ISSUE THREAD

**Issue by Concept211** [tas2580/phpBB-3-1-SEO-URLs#21]
Would it be possible to also make SEO-friendly URLs for all other pages such as the FAQ, Search, Members, etc?

**Comment by tas2580** [comment]
FAQ is just faq.php, OK, I can rewrite it to faq.html, but why?
Search does not make sense because it should not be indexed.
Also the member pages have no content and should not be indexed, so rewriting is not necessary.

**Comment by Concept211** [comment]
Yeah, I suppose you're right. I just wanted the entire board to consistently hide all .php extensions in the URLs.

**Comment by Galixte** [comment]
but it’s only cosmetic.
