### ISSUE TITLE
Problem with links on forum's home page

### ISSUE THREAD

**Issue by ghost** [tas2580/phpBB-3-1-SEO-URLs#23]
http://forum.pieknyumysl.com/

When I use this forum extension, I have problem with links on forum's home page.
For example:
http://forum.pieknyumysl.com/pami%C4%99%C4%87-f35/-t.html#p77
Instead:
http://forum.pieknyumysl.com/schizofrenia-f35/objawy-schizofrenii-t42.html

Error is when forum have subforum.

**Comment by baxterbln** [comment]
I can confirm this bug:

Small dirty fix:
in listener.php (line 137) add the follow code:

$last_post_title = $this->base->title_to_url($event['row']['forum_last_post_subject']);
$forum_row['U_LAST_POST'] = str_replace("t.html", "t".$event['row']['forum_last_post_id'].".html", $forum_row['U_LAST_POST']);
$forum_row['U_LAST_POST'] = str_replace("/-t", "/$last_post_title-t", $forum_row['U_LAST_POST']);
