### ISSUE TITLE
Need use links like this:

### ISSUE THREAD

**Issue by MESWEB** [tas2580/phpBB-3-1-SEO-URLs#25]
site.com/forumname/topicname
without a forum and others ID.

**Comment by tas2580** [comment]
And what is if there are 2 topics or forums with the same title?

**Comment by MESWEB** [comment]
Maybe then mod should put increased number to the url or better if mod find full name of url and show message like this "sorry You can't post this topic - url.com/forumname/topicname - this topic is already started".

**Comment by tas2580** [comment]
Ok, but than you have to store the URL in the database. What is with old forums/topics?

Also you need to change every database query. I don't think that this is possible with events, so you would need changes in the core code.
