### ISSUE TITLE
post issues (avatar/contact)

### ISSUE THREAD

**Issue by petters0n** [tas2580/phpBB-3-1-SEO-URLs#3]
me again:)
found another bug:
http://i58.tinypic.com/jv13cg.jpg

idea:
It seems that {postrow.U_POST_AUTHOR} variable from viewtopic.php has wrong value which causes issue with avatar and contact button.

this only happens if u are logged out (guest) - not if u are logged in....

**Comment by Sarr** [comment]
I too have this problem. Please find time to help us tas2580.
ps. I fixed it by commenting out the part in events/listener, where it tries to disable username links for guests :). It doesn't remove links then, but fixes the problem with QuickReply Reloaded Ext.

**Comment by tas2580** [comment]
Removed disable username links from extension
