### ISSUE TITLE
Attachment filetype images are broken

### ISSUE THREAD

**Issue by HanPrower** [tas2580/phpBB-3-1-SEO-URLs#35]
The attachment filetype images are broken due to looking for them in ./images (by default).

I wrote a _terrible_ fix for it (which has issues):
`'core.parse_attachments_modify_template_data'			=> 'parse_attachments_modify_template_data',`

```
	/**
	 * Correct the path of attachment images
	 *
	 * @param	object	$event	The event object
	 * @return	null
	 * @access	public
	 */
	public function parse_attachments_modify_template_data($event)
	{
		$loc = $this->request->server('REQUEST_URI');
		if (!strpos($loc, 'viewtopic'.$this->php_ext)) {
			$block_array = $event['block_array'];
			$block_array['UPLOAD_ICON'] = str_replace('img src=".', 'img src="..', $block_array['UPLOAD_ICON']);
			$event['block_array'] = $block_array;
		}
	}
```

**Comment by tas2580** [comment]
Images should go over download/file.php?id=123

**Comment by HanPrower** [comment]
@tas2580 what do you mean by that?

You haven't presented a fix to the issue that the icons that show the filetype of an attachment are broken when using this extension.

This icon:
![image](https://user-images.githubusercontent.com/1781312/34406938-a2ee8876-ebb3-11e7-9e76-1c90175e97c9.png)
