### ISSUE TITLE
Does not work with 3.2.*

### ISSUE THREAD

**Issue by ghost** [tas2580/phpBB-3-1-SEO-URLs#50]
Failed to make it work on PHPBB 3.2.0 and 3.2.1

Original URL: https://www.forum.2globalnomads.info/viewforum.php?f=16&sid=34457ad32718c24b2a7ac6eacac39de6

The same URL using extension: https://www.forum.2globalnomads.info/it-hosting-blogging-and-gaming-f16/?sid=4469276c64146ba64432ffa710a6ad63

**Result:** No route found for "GET /it-hosting-blogging-and-gaming-f16/" (from "https://www.forum.2globalnomads.info/")

**Comment by tas2580** [comment]
https://github.com/tas2580/seourls/wiki/Webserver-configuration

**Comment by ghost** [comment]
Great, thanks a lot! I will test that right away.

**Comment by ghost** [comment]
This fix does not work. It resets the forum style to default and breaks sitemap.xml  (phpBB3 SEO Sitemap 1.1.1). Please re-open the ticket.
