### ISSUE TITLE
Does not work with 3.2.*

### ISSUE THREAD

**Issue by ghost** [tas2580/phpBB-3-1-SEO-URLs#51]
I failed to get this mod working on PHPBB 3.2.0 and 3.2.1

[Proposed fix](https://github.com/tas2580/seourls/wiki/Webserver-configuration) is not working. It resets the forum style to the default removing all custom styles, and conflicts with phpBB3 SEO Sitemap 1.1.1 which is not showing the new SEO URLs as it should.

Original issue:

Original URL: https://www.forum.2globalnomads.info/viewforum.php?f=16

The same URL using extension: https://www.forum.2globalnomads.info/it-hosting-blogging-and-gaming-f16/

Result: No route found for "GET /it-hosting-blogging-and-gaming-f16/" (from "https://www.forum.2globalnomads.info/")

**Comment by ukdev** [comment]
I had the same problem using apache httppd. I managed to work-around this.

The phpBB 3.2 installation comes with some pre-configured rewrites taking place, specifically:

    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)$ app.php [QSA,L]

The additional re-write rules that need to be added for this plugin need to be added *BEFORE* these existing rewrite conditions.

**Comment by jamiewastin** [comment]
I had the same problem using apache httppd. I managed to work-around this.

The phpBB 3.2 installation comes with some pre-configured rewrites taking place, specifically:

    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)$ app.php [QSA,L]

The additional re-write rules that need to be added for this plugin need to be added *BEFORE* these existing rewrite conditions.

**Comment by ghost** [comment]
Ì had them there before pre-configured rewrites and they broke my style. Do you have your own style or default? Is your sitemap working?

**Comment by gmbb** [comment]
Ì had them there before pre-configured rewrites too and they broke my Javascript:
SyntaxError: expected expression, got '<'

and this means the first row `<!DOCTYPE html>`

**Comment by Caroga** [comment]
Will support for 3.2.x be included?

**Comment by Galixte** [comment]
Completely useless tool, not compatible with a lot extensions which add a new page on the board, and more importantly (IMHO) to obtain a good results on the engine this kind of SEO tool don’t help you (a few years earlier yes, currently not anymore), the good way is to publish original contents from time to time, nothing else.

Moreover the author has abandonned development for his extensions, see his GitHub profile, you shouln’t expect any update in the future.

**Comment by tas2580** [comment]
https://github.com/tas2580/seourls/wiki/Webserver-configuration
