### ISSUE TITLE
Search results are not rewritten

### ISSUE THREAD

**Issue by RonaldKools** [tas2580/phpBB-3-1-SEO-URLs#56]
When you use phpBB's search functionality, you get topic URLs that are not yet rewritten.

**Comment by tas2580** [comment]
Search engines don't use the search function

**Comment by RonaldKools** [comment]
Correct, but forumusers that use the search might share the URL of the topic they find. It think it would be nice from a UX point of view if all topic URLs would look the same.

**Comment by tas2580** [comment]
Sure it would be nice, but the problem is the "hilit" parameter. 
But I can try to rewrite all URLs without parameters.

**Comment by RonaldKools** [comment]
I see your point... the hilit param is also in the URL. Hmm....
