### ISSUE TITLE
Problem: Reply with quote

### ISSUE THREAD

**Issue by LuigiMdg** [tas2580/phpBB-3-1-SEO-URLs#57]
The problem would seem to be due to the fact that sometimes clicking on _Reply with quote_ is not redirected to the root _posting.php_ file, but the category before the file is added ..!

For example, instead of:

> website.com/posting.php?mode=quote&f=21&p=16202

You are redirected to:

> website.com/**category-f1**/posting.php?mode=quote&f=21&p=16202

Please, if you do not have time to correct, could you at least tell me which function to check again?
Thanks so much

**Comment by tas2580** [comment]
Reply with quote works on my testinstalation
