### ISSUE TITLE
Please add option - simple url

### ISSUE THREAD

**Issue by MESWEB** [tas2580/phpBB-3-1-SEO-URLs#9]
This mod should be able to change url to simple url like: website.com/board/thread/postname
without f-id and post id in url. How to change this?

**Comment by tas2580** [comment]
For that I need to change all SQL querys to get the forums/topics. Also there is the problem that topics/forums can have the same title. So this is not possible.

**Comment by MESWEB** [comment]
It is possible. Links looking like ForumName/BoardName/1/TopicName 
where 1 is id topic but board name is unique name.

**Comment by tas2580** [comment]
What is the advantage of ForumName/BoardName/1/TopicName  to ForumName/BoardName-f1/TopicName-t1.html?

Without the Forum ID I have to change all SQL queries that get the forums and I think that is not possible with events.
You can hide the ID of the forums and map it in your htaccess file. But this would be a custom change that you can do by your self.
